-- +goose Up
ALTER TABLE artist_profiles
    ADD COLUMN IF NOT EXISTS handle TEXT UNIQUE,
    ADD COLUMN IF NOT EXISTS born TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS discipline TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tagline TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS years_active TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS portrait_url TEXT NOT NULL DEFAULT '';

UPDATE artist_profiles SET handle = slug WHERE handle IS NULL;

ALTER TABLE art_posts
    ADD COLUMN IF NOT EXISTS year INT,
    ADD COLUMN IF NOT EXISTS dimensions TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS style TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS featured_acquisition BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS palette TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'General',
    ADD COLUMN IF NOT EXISTS excerpt TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reading_time INT NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS difficulty TEXT NOT NULL DEFAULT 'Beginner',
    ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS contributors INT NOT NULL DEFAULT 1;

ALTER TABLE events
    ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE,
    ADD COLUMN IF NOT EXISTS event_type TEXT NOT NULL DEFAULT 'Opening',
    ADD COLUMN IF NOT EXISTS venue TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE events
    DROP COLUMN IF EXISTS city,
    DROP COLUMN IF EXISTS venue,
    DROP COLUMN IF EXISTS event_type,
    DROP COLUMN IF EXISTS slug;

ALTER TABLE articles
    DROP COLUMN IF EXISTS contributors,
    DROP COLUMN IF EXISTS verified,
    DROP COLUMN IF EXISTS difficulty,
    DROP COLUMN IF EXISTS reading_time,
    DROP COLUMN IF EXISTS excerpt,
    DROP COLUMN IF EXISTS category;

ALTER TABLE art_posts
    DROP COLUMN IF EXISTS palette,
    DROP COLUMN IF EXISTS featured_acquisition,
    DROP COLUMN IF EXISTS style,
    DROP COLUMN IF EXISTS city,
    DROP COLUMN IF EXISTS dimensions,
    DROP COLUMN IF EXISTS year;

ALTER TABLE artist_profiles
    DROP COLUMN IF EXISTS portrait_url,
    DROP COLUMN IF EXISTS featured,
    DROP COLUMN IF EXISTS years_active,
    DROP COLUMN IF EXISTS tagline,
    DROP COLUMN IF EXISTS discipline,
    DROP COLUMN IF EXISTS born,
    DROP COLUMN IF EXISTS handle;
