FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /api ./cmd/api

FROM gcr.io/distroless/static-debian12

WORKDIR /
COPY --from=builder /api /api
COPY migrations /migrations

ENV HTTP_PORT=8080
EXPOSE 8080

USER nonroot:nonroot
ENTRYPOINT ["/api"]
